---
- name: test a playbook
  hosts: webserver
  become: yes
  tasks:
  - name: install httpd package
    yum:
      name: httpd
      state: installed
  - name: httpd service start
    service:
      name: httpd
      state: started

